/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface;

import Business.VitalSign;
import Business.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author He_Fangning_001664202
 */
public class CreateVitalSignJPanel extends javax.swing.JPanel {
    private VitalSignHistory vitalSignHistory;
    private VitalSign vs;
    
    public boolean Letter(String s){
        for(int i=0;i<s.length();i++){
        if(!(s.charAt(i)>='A'&&s.charAt(i)<='Z') && !(s.charAt(i)>='a'&&s.charAt(i)<='z')){
            return false;
            }
        }return true;
    }
    public boolean isNumeric(String str){

         for (int i = str.length();--i>=0;){
             if (!Character.isDigit(str.charAt(i))){
                 return false;
             }
         }
         return true;
    }

    /**
     * Creates new form CreatePatientPanel
     */
    public CreateVitalSignJPanel(VitalSignHistory vsh) {
        initComponents();
         this.vitalSignHistory = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtBloodPressure = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRespiratoryRate = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Weight");

        jLabel4.setText("Heart Rate");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Create Vital Sign");

        jLabel1.setText("Blood Pressure");

        jLabel2.setText("Respiratory Rate  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtRespiratoryRate)
                            .addComponent(txtWeight)
                            .addComponent(txtHeartRate)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 404, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addComponent(btnSave)
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if("".equals(txtBloodPressure.getText().trim())||"".equals(txtHeartRate.getText().trim())||
            "".equals(txtRespiratoryRate.getText().trim())||"".equals(txtWeight.getText().trim())
            ){                       //all empty
            JOptionPane.showMessageDialog(null, "Please complete all information !","Error",
                JOptionPane.WARNING_MESSAGE);
        }else if(!isNumeric(txtBloodPressure.getText().trim())){
             JOptionPane.showMessageDialog(null, "Invalid Blood Pressure!");
             
         }else if(!isNumeric(txtHeartRate.getText().trim())){
             JOptionPane.showMessageDialog(null, "Invalid Heart Rate!");
          }else if(!isNumeric(txtRespiratoryRate.getText().trim())){
             JOptionPane.showMessageDialog(null, "Invalid Respiratory Rate!");
           }else if(!isNumeric(txtWeight.getText().trim())){
             JOptionPane.showMessageDialog(null, "Invalid Weight!");
            }
           else{
            VitalSign vitalSign = vitalSignHistory.createVitalSign();
            vitalSign.setBloodPressure(Integer.parseInt(txtBloodPressure.getText().trim()));
            vitalSign.setHeartRate(Integer.parseInt(txtHeartRate.getText().trim()));
            vitalSign.setRespiratoryRate(Integer.parseInt(txtRespiratoryRate.getText().trim()));
            vitalSign.setWeight(Double.parseDouble(txtWeight.getText().trim()));
            vitalSign.setDate();
          

            JOptionPane.showMessageDialog(null, "Vital Sign saved successfully");
            txtBloodPressure.setText("");
            txtHeartRate.setText("");
            txtRespiratoryRate.setText("");
            txtWeight.setText("");

       
        
        
        }
         
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
